version: '3.9'
services:
  php:
    build: .
    ports: 
      - "5000:80"
    volumes:
      - ../src:/var/www/html

  postgres: 
    image: postgres:latest
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Teste@123
      POSTGRES_DB: simple-crud
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"

volumes: 
  db_data:
